/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myclassblockinterface;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class asignaturasGui extends javax.swing.JInternalFrame {
    
    principalGui gui;
    ArrayList <JButton> botones;

    
    public asignaturasGui(principalGui gui){
        initComponents();
        this.gui = gui;
        botones = new ArrayList<>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panelContenedor = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        agregarAsig = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);
        setTitle("ClassBlock: asignaturas");

        panelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelContenedor.setLayout(new java.awt.GridLayout(6, 2, 0, 3));
        jScrollPane1.setViewportView(panelContenedor);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Asignaturas");

        agregarAsig.setBackground(new java.awt.Color(0, 102, 153));
        agregarAsig.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregarAsig.setForeground(new java.awt.Color(255, 255, 255));
        agregarAsig.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/agregarIcon.png"))); // NOI18N
        agregarAsig.setText("Nueva");
        agregarAsig.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarAsigActionPerformed(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(0, 102, 153));
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(255, 255, 255));
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/configIcon.png"))); // NOI18N
        jButton4.setText("Administrar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(agregarAsig, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1))
                        .addGap(0, 192, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 545, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(agregarAsig, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarAsigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarAsigActionPerformed

        gui.addAsig.setVisible(true);
        gui.addAsig.requestFocus(); 
        
    }//GEN-LAST:event_agregarAsigActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        String asignatura = JOptionPane.showInputDialog(null,"Ingrese en nombre de la asignatura a editar","Editar Asignatura",1);
        boolean encontrado = false;
        int idEncontrada = -1;
        
        for (int i = 0; i < gui.asig.botones.size(); i++) {
            if(asignatura.equals(gui.app.getUsuario().getAsignaturas().get(i).getNombre())){
                encontrado = true;
                idEncontrada = i;
                break;
            }
        }

        if(encontrado){
            gui.editAsig.setTitle(title);
            gui.editAsig.asignatura = gui.app.getUsuario().getAsignaturas().get(idEncontrada).getNombre();
            gui.editAsig.maestro = gui.app.getUsuario().getAsignaturas().get(idEncontrada).getDocente();            
            gui.editAsig.enlace = gui.app.getUsuario().getAsignaturas().get(idEncontrada).getLinkAsig();
            gui.editAsig.descripcion = gui.app.getUsuario().getAsignaturas().get(idEncontrada).getDescripcion();
            gui.editAsig.idAsignatura = idEncontrada;
            gui.editAsig.colocarDatos();
            gui.editAsig.setVisible(true);
            gui.editAsig.requestFocus(); 
        }else{
            JOptionPane.showMessageDialog(null, "La asignatura no fue encontrada: no existe o está mal escrita","Administrar",0);
        }
        
    }//GEN-LAST:event_jButton4ActionPerformed

    public void actualizarGui(){
        try{
            panelContenedor.removeAll();
            botones.clear();
            for (int i = 0; i < gui.app.getUsuario().getAsignaturas().size(); i++) {
                gui.app.getUsuario().getAsignaturas().forEach(asignatura -> asignatura.cargarActividades());
                
                Color colorFondo = new Color(0,102,153);
                // Atributos del botón
                JButton boton = new JButton(gui.app.getUsuario().getAsignaturas().get(i).getNombre());
                boton.setBackground(colorFondo);
                boton.setForeground(Color.white);
                boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/newnewlibroIcon.png")));
                boton.setFont(new java.awt.Font("Tahoma", 1, 18));
                boton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
                panelContenedor.add(boton);
                botones.add(i, boton);

                String descr = gui.app.getUsuario().getAsignaturas().get(i).getDescripcion();
                showActivities actividades = new showActivities(this.gui);
                gui.actividades.add(actividades);
                gui.actividades.get(i).setTextoAsign(gui.app.getUsuario().getAsignaturas().get(i).getNombre() + ": Actividades");
                gui.actividades.get(i).setNombreMaestro("Nombre del maestro : " + gui.app.getUsuario().getAsignaturas().get(i).getDocente());
                gui.actividades.get(i).setEnlaceAsignatura("Enlace a la asignatura : " + gui.app.getUsuario().getAsignaturas().get(i).getLinkAsig());
                gui.actividades.get(i).setDescripcionAsignatura("Descripción de la asginatura : " + descr);
                gui.actividades.get(i).requestFocus();
                
                botones.get(i).addActionListener(new ActionListener() {
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        int identificador = -1;
                        for(int i = 0 ; i < botones.size() ; i++){
                            if(boton.getText() == botones.get(i).getText()){
                                identificador = i;
                                break;
                            }
                        }
                        gui.actividades.get(identificador).setVisible(true);
                        gui.actividades.get(identificador).position = identificador;
                        gui.actividades.get(identificador).setTitle(gui.app.getUsuario().getAsignaturas().get(identificador).getNombre());
                        gui.asignar(gui.actividades.get(identificador));
                        gui.actividades.get(identificador).actualizar();
                        gui.actividades.get(identificador).toFront();                         
                    }
                });

            }
            panelContenedor.updateUI();
        }catch(java.lang.IllegalArgumentException e){}
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton agregarAsig;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panelContenedor;
    // End of variables declaration//GEN-END:variables
}
