/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myclassblockinterface;

import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author David
 */
public class showActivities extends javax.swing.JInternalFrame {

    ArrayList <JButton> botones = new ArrayList<>();
    ArrayList <detalleActividad> detAct = new ArrayList<>();

    principalGui gui;
    int position;

    public showActivities(principalGui gui) {
        initComponents();
        this.gui = gui;
    }
    
    

    public JLabel getDescripcionAsignatura() {
        return descripcionAsignatura;
    }

    public void setDescripcionAsignatura(String text) {
        this.descripcionAsignatura.setText(text);
    }

    public JLabel getEnlaceAsignatura() {
        return enlaceAsignatura;
    }

    public void setEnlaceAsignatura(String text) {
        this.enlaceAsignatura.setText(text);
    }

    public JLabel getNombreMaestro() {
        return nombreMaestro;
    }

    public void setNombreMaestro(String text) {
        this.nombreMaestro.setText(text);
    }

    public JLabel getTextoAsign() {
        return textoAsign;
    }

    public void setTextoAsign(String text) {
        this.textoAsign.setText(text);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        nombreMaestro = new javax.swing.JLabel();
        enlaceAsignatura = new javax.swing.JLabel();
        descripcionAsignatura = new javax.swing.JLabel();
        textoAsign = new javax.swing.JLabel();
        panelContenedor = new javax.swing.JPanel();
        agregarActividad = new javax.swing.JButton();
        administraActiv = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setResizable(true);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        nombreMaestro.setText("Nombre del maestro : texto de ejemplo");

        enlaceAsignatura.setText("Enlace a la asignatura : texto de ejemplo");

        descripcionAsignatura.setText("Descripción de la asginatura : texto de ejemplo");

        textoAsign.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        textoAsign.setText("Texto de ejemplo : Actividades");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textoAsign, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(nombreMaestro)
                            .addComponent(enlaceAsignatura)
                            .addComponent(descripcionAsignatura))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textoAsign, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nombreMaestro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enlaceAsignatura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descripcionAsignatura)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        panelContenedor.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelContenedor.setLayout(new java.awt.GridLayout(6, 2, 0, 3));

        agregarActividad.setBackground(new java.awt.Color(0, 102, 153));
        agregarActividad.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        agregarActividad.setForeground(new java.awt.Color(255, 255, 255));
        agregarActividad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/agregarIcon.png"))); // NOI18N
        agregarActividad.setText("Nueva Actividad");
        agregarActividad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActividadActionPerformed(evt);
            }
        });

        administraActiv.setBackground(new java.awt.Color(0, 102, 153));
        administraActiv.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        administraActiv.setForeground(new java.awt.Color(255, 255, 255));
        administraActiv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/configIcon.png"))); // NOI18N
        administraActiv.setText("Administrar");
        administraActiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                administraActivActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(agregarActividad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(administraActiv, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 234, Short.MAX_VALUE))
                    .addComponent(panelContenedor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelContenedor, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(administraActiv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(agregarActividad, javax.swing.GroupLayout.DEFAULT_SIZE, 67, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void agregarActividadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActividadActionPerformed
        gui.addAct.position = this.position;
        gui.addAct.setVisible(true);
        gui.addAct.asignatura = this.getTitle();
        gui.addAct.setLabelTitulo(this.getTitle() + ": Actividades");
    }//GEN-LAST:event_agregarActividadActionPerformed

    private void administraActivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_administraActivActionPerformed
        
        try{
        
        String asignatura = JOptionPane.showInputDialog(null,"Ingrese en nombre de la actividad a editar","Editar actividad",1);
        boolean encontrado = false;
        int idEncontrada = -1;
        
            for (int i = 0; i < this.botones.size(); i++) {
                if(asignatura.equals(gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(i).getTitulo())){
                    encontrado = true;
                    idEncontrada = i;
                    break;
                }
            }

        if(encontrado){
            gui.editAct.calificacionMaxima = gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(idEncontrada).getCalificacionMaxima();
            gui.editAct.calificacionObtenida = gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(idEncontrada).getCalificacionObtenida();
            gui.editAct.descripcion = gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(idEncontrada).getDescripcion();
            gui.editAct.estadoDeEntrega = gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(idEncontrada).getEstadoDeEntrega();
            gui.editAct.fechaDeEntrega = gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(idEncontrada).getFechaDeEntrega();
            gui.editAct.tipoDeActividad = gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(idEncontrada).getTipoDeActividad();
            gui.editAct.titulo = gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(idEncontrada).getTitulo();
            gui.editAct.posAsignatura = this.position;
            gui.editAct.posActividad = idEncontrada;
            gui.editAct.colocarDatos();
            gui.editAct.setVisible(true);
        }else{
            JOptionPane.showMessageDialog(null, "La actividad no fue encontrada: no existe o está mal escrita","Administrar",0);
        }
        
        }catch(NullPointerException ex){}
    }//GEN-LAST:event_administraActivActionPerformed

    public void actualizar(){
        botones.clear();
        panelContenedor.removeAll();
        this.detAct.clear();
        for (int i = 0; i < gui.app.getUsuario().getAsignaturas().get(position).getActividades().size(); i++) {
                Color colorRed = new Color(207,152,149);
                Color colorGreen = new Color(160,207,149);

                // Atributos del botón
                JButton boton = new JButton(gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(i).getTitulo());
                boton.setForeground(Color.white);
                boton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/lapizIcon.png")));
                boton.setFont(new java.awt.Font("Tahoma", 1, 18));
                boton.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
                panelContenedor.add(boton);
                botones.add(i, boton);
                                
                detalleActividad detAct = new detalleActividad(this.gui);
                
                if(gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(i).getEstadoDeEntrega().equals("Entregado")){
                    detAct.setCbEntrega(true);
                    boton.setBackground(colorGreen);
                }else{
                    detAct.setCbEntrega(false);
                    boton.setBackground(colorRed);
                }
                //String fecha = (gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(i).getFechaDeEntrega().get(Calendar.DATE));
                
                detAct.setLabelTitulo(gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(i).getTitulo());
                detAct.setTfCalifMax(String.valueOf(gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(i).getCalificacionMaxima()));
                detAct.setTfCalifmin(String.valueOf(gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(i).getCalificacionObtenida()));
                detAct.setTaDescripcion(gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(i).getDescripcion());
                detAct.setTfTipoActividad(gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(i).getTipoDeActividad());
                detAct.setjCalendar1(gui.app.getUsuario().getAsignaturas().get(position).getActividades().get(i).getFechaDeEntrega());
                detAct.posAsignatura = position;
                detAct.posActividad = i;
                
                this.detAct.add(detAct);
                
                botones.get(i).addActionListener(new ActionListener(){
                    @Override
                    public void actionPerformed(ActionEvent e) {
                        int identificador = -1;
                        for (int j = 0; j < botones.size(); j++) {
                            if(boton.getText() == botones.get(j).getText()){
                                identificador = j;
                                break;
                            }
                        }if(identificador != -1){
                            System.out.println(" ID = " + identificador);
                            gui.asignarAct(gui.actividades.get(position).detAct.get(identificador));
                            gui.actividades.get(position).detAct.get(identificador).setFocusCycleRoot(true);
                            gui.actividades.get(position).detAct.get(identificador).setVisible(true);
                            gui.actividades.get(position).detAct.get(identificador).toFront();
                            gui.actividades.get(position).detAct.get(identificador).setTitle("Actividad: " + gui.actividades.get(position).detAct.get(identificador).getLabelTitulo());
                        }else{
                            JOptionPane.showMessageDialog(null, "Error fatal", "Error",0);
                        }
                    }
                   });

        }
        panelContenedor.updateUI();
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton administraActiv;
    public javax.swing.JButton agregarActividad;
    private javax.swing.JLabel descripcionAsignatura;
    private javax.swing.JLabel enlaceAsignatura;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel nombreMaestro;
    private javax.swing.JPanel panelContenedor;
    private javax.swing.JLabel textoAsign;
    // End of variables declaration//GEN-END:variables
}
